catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("books/", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),

]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
# development only
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instance


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author is a string rather than an object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='isbn numba, foo!')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ", ".join(genre.name for genre in self.genre.all()[:3])
    display_genre.short_description = 'genre'

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/views.py
from django.shortcuts import render
from .models import Author, Book, BookInstance, Language, Genre
from django.views import generic

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status="a").count()
    num_authors = Author.objects.count()
    num_sex_genres = Genre.objects.filter(name="erotica").count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_sex_genres": num_sex_genres,
        "num_visits": num_visits,
    }
    return render(request, "index.html", context=context)


class BookListView(generic.ListView):
    model = Book
    template_name = "book_list.html"
    paginate_by = 4


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book_detail.html'


class AuthorListView(generic.ListView):
    model = Author
    template_name = "author_list.html"


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = "author_detail.html"


# Create your views here.

catalog/templates/author_detail.html
{% extends "base_generic.html" %}

{% block header %}
  <h1 style="padding-right: 100px; font-size: 75px;"> Author: {{ author.last_name }}, {{ author.first_name }} </h1>
                 {% endblock %}
{% block content %}


  <p><strong>First Name:</strong> {{ author.first_name }}</p> <!-- author detail link not yet defined -->
  <p><strong>Last Name:</strong> {{ author.last_name }}</p>
  <p><strong>Date of Birth:</strong> {{ author.date_of_birth }}</p>
<!--  <p><strong>Date of Death:</strong> {{ author.date_of_death }}</p>-->

  <ul class="list-group">
<li class="list-group-item center_body middle" style="background-color: #ffffff30"><strong class="m-3" style="font-size: 30px;">Books By This Author:</strong></li>
{% for book in author.book_set.all %}
<li class="list-group-item center_body middle" style="background-color: #ffffff30">
        <a style=" color: #a55439" class="center_body middle" href="{{ book.get_absolute_url }}">{{ book }}</a>
      </li>
{% endfor %}
  </ul>
{% endblock %}

catalog/templates/author_list.html
{% extends "base_generic.html" %}


{% block header %}

 <h1 style="font-size: 75px;">Author List</h1>
            {% endblock %}
{% block content %}

  {% if author_list %}
  <ul class="list-group">
    {% for author in author_list %}
    <li class="list-group-item center_body middle"  style="background-color: #ffffff30; color: #749aac">
        <a style=" color: #a55439; font-size: 25px" class="center_body middle" href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}</a> born: {{ author.date_of_birth }}
      </li>
    {% endfor %}
  </ul>
  {% else %}






    <p>fuck you</p>











  {% endif %}














{% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <style>
a {
background-color: #ffffff00;
color: #a55439;
}

strong {
 color:#b06c45;
 font-family: suranna;
 background-color: #ffffff00;
 font-size: 20px;
}
p {
 color:#b06c45;
 font-family: suranna;
 background-color: #ffffff00;
 font-size: 20px;
 color: #749aac;>
}

.center_body {
  margin: auto;
  width: 80%;
  padding: 20px;
}
 body {
    background: white url("/static/images/background.png") no-repeat center center fixed;
     -webkit-background-size: cover;
     -moz-background-size: cover;
     -o-background-size: cover;
      background-size: cover;
}

h1 {
 color:#a55439;
 font-family: z003;
 font-size: 75px;
 text-shadow: 2px 2px #749aac;
 margin-bottom: auto;
 padding-bottom: 0%;
 }

.middle {
 color:#b06c45;
 font-family: suranna;
 background-color: #ffffff00;
 font-size: 20px;
 }


    </style>
  {% block title %}<title>Library</title>{% endblock %}
    <link rel="icon" href='{% static "images/favicon.ico" %}'>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<!--  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
  <!-- Add additional CSS in static file -->
     <!-- Latest compiled and minified CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <nav class="navbar navbar-expand-sm fixed-top" style="background-color: #e98a4a50;">
          <a href="{% url 'index' %}">
     <img src='{% static "images/logo.png" %}' alt="books" width="100" height="100" style="margin-left: 15px;" >
    </a>
<div class="col-sm-4"></div>
        <div class="collapse navbar-collapse col-sm-8 justify-content-left">
            {% block header %}

            {% endblock %}
        </div>
</nav>

</head>
<body style="height: 100vh;">
  <div class="container-fluid h-100 margin-top: 100px;">

          <div class="row h-100">
      <div class="col-sm-1 h-200" style="background-color:#b06c4520;" >
      {% block sidebar %}

 <div style="margin-top: 110px; color:#a55439;" class="col-sm-12" >
        <ul class="nav flex-column" style="position:fixed">

          <li class="nav-item text-start m-4">
            <a style="color: #74412c" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item text-start m-4">
            <a style="color: #74412c" href="{% url 'books' %}">All books</a>
          </li>
          <li class="nav-item text-start m-4">
            <a style="color: #74412c" href="{% url 'authors' %}">All authors</a>
          </li>
        </ul>
      </div>
     {% endblock %}
      </div>
              <div class="col-sm-1"></div>
      <div style="margin-top: 140px;" class="col-sm-10">{% block content %}{% endblock %}
      {% block pagination %}
    {% if is_paginated %}
        <div class="pagination middle center_body" style="padding-left: 250px; background-color: #ffffff00;">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a class="center_body" style=" color: #a55439" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a class="center_body" style=" color: #a55439" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}

      </div>
    </div>
  </div>
</body>
</html>

catalog/templates/book_detail.html
{% extends "base_generic.html" %}

{% block header %}
  <h1 style="font-size: 75px;">Title: {{ book.title }}</h1>
        {% endblock %}
{% block content %}

  <p><strong>Author:</strong> <a style="color: #749aac;" href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-right:20px;margin-top:20px">
    <h4 style="width: 100%; padding: 5px; color:#a55439; background-color: #ffffff00; font-size: 30px" class="center_body middle"><strong>Copies</strong></h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}
  style="color: #749aac;"

catalog/templates/book_list.html
{% extends "base_generic.html" %}


{% block header %}

 <h1 style="font-size: 75px;">Book List</h1>
            {% endblock %}

{% block content %}

  {% if book_list %}
  <ul class="list-group">
    {% for book in book_list %}
      <li class="list-group-item center_body middle"  style="background-color: #ffffff30; color: #749aac">
        <a class="center_body middle" style=" color: #a55439"  href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}

{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block header %}

<h1 style="font-size: 75px" xmlns="http://www.w3.org/1999/html">Library Home </h1>
            {% endblock %}

{% block content %}
<!--  <h1>Local Library Home</h1>-->
<div class="center_body middle" style="background-color: #ffffff30;">
  <h2 class="center_body middle" style="font-size: 40px; background-color: #ffffff00;">Compelling content</h2>
  <p class="center_body middle" style="font-size: 25px; background-color: #ffffff00;">The library has the following record counts:</p>
  <ul class="center_body middle" style="background-color: #ffffff00;">
    <li>Books: {{num_books}}</li>
    <li>Copies: {{ num_instances }}</li>
    <li>Copies available:{{ num_instances_available }}</li>
    <li>Authors: {{ num_authors }}</li>


  </ul>
  <p class="center_body middle" style="font-size: 25px; background-color: #ffffff00;">You have visited this page <span style="color: #749aac;"> {{ num_visits }}</span> time{{ num_visits|pluralize }}.</p>
  </div>
{% endblock %}